# Generated by Django 5.1.7 on 2025-04-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0002_startup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='industry_type',
            field=models.CharField(choices=[('tech', 'Technology'), ('fintech', 'Fintech'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('retail', 'Retail'), ('manufacturing', 'Manufacturing'), ('transportation', 'Transportation'), ('agriculture', 'Agriculture'), ('real_estate', 'Real Estate'), ('entertainment', 'Entertainment'), ('food_beverage', 'Food & Beverage'), ('energy', 'Energy'), ('telecommunications', 'Telecommunications'), ('biotechnology', 'Biotechnology'), ('pharmaceuticals', 'Pharmaceuticals'), ('automotive', 'Automotive'), ('aerospace', 'Aerospace'), ('construction', 'Construction'), ('hospitality', 'Hospitality'), ('insurance', 'Insurance'), ('media', 'Media'), ('other', 'Other')], max_length=50),
        ),
    ]
