# Generated by Django 5.1.7 on 2025-04-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0003_alter_startup_industry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='industry_type',
            field=models.CharField(choices=[('tech', 'Technology'), ('fintech', 'Fintech'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('other', 'Other')], max_length=50),
        ),
    ]
