# Generated by Django 5.1.7 on 2025-04-08 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0006_offer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
