# Generated by Django 5.1.7 on 2025-04-08 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_monthlyprofit'),
        ('startup', '0007_delete_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equity_percentage', models.DecimalField(decimal_places=2, help_text='Percentage of equity offered', max_digits=5)),
                ('royalty_percentage', models.DecimalField(decimal_places=2, help_text='Percentage of royalty offered', max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='accounts.investorprofile')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='startup.startup')),
            ],
        ),
    ]
