# Generated by Django 5.2 on 2025-04-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0009_alter_startup_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='royalty_percentage',
        ),
        migrations.AddField(
            model_name='offer',
            name='details',
            field=models.TextField(blank=True, help_text='Additional details of the offer', null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='investment_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount of investment offered', max_digits=12),
        ),
        migrations.AddField(
            model_name='offer',
            name='response_date',
            field=models.DateTimeField(blank=True, help_text='When the startup responded to the offer', null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='viewed_by_startup',
            field=models.BooleanField(default=False, help_text='Whether the startup has viewed this offer since the last update'),
        ),
    ]
