# Generated by Django 5.2 on 2025-04-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0010_remove_offer_royalty_percentage_offer_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='royalty_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage of revenue as royalty', max_digits=5),
        ),
    ]
